/**
 * @fileoverview UserRepository — Data access layer for User authentication data.
 * Provides methods to check PIN status, retrieve the user, create a user,
 * and persist authentication state changes back to the database.
 * @module lib/UserRepository
 * @author Karim Ashraf Ahmed, Eyad Hatem Fouad, Sherif Ahmed Metwally, Ahmed Sherif Ahmed
 */

import SQLiteHelper from './SQLiteHelper';
import User from '@/models/User';

/**
 * @class UserRepository
 * @classdesc Handles all database operations related to the single application User.
 * Since Masroofy is a single-user personal finance app, the User table
 * contains at most one row. All methods are designed around this constraint.
 */
class UserRepository {
    /**
     * Creates a new UserRepository and connects to the shared database instance.
     */
    constructor() {
        this.db = SQLiteHelper.getInstance().getWritableDatabase();
    }

    /**
     * Checks whether a PIN has already been configured for the application.
     * Used on app launch to determine whether to redirect to /login or /signup.
     * @returns {boolean} True if a user row with a non-null pinHash exists, false otherwise.
     */
    isPinSet() {
        const row = this.db.prepare('SELECT id FROM User WHERE pinHash IS NOT NULL LIMIT 1').get();
        return !!row;
    }

    /**
     * Retrieves the single user record from the database and wraps it in a User model instance.
     * The User model instance provides access to authentication methods like verifyPin() and isLockedOut().
     * @returns {User|null} A User model instance, or null if no user exists.
     */
    getUser() {
        const row = this.db.prepare('SELECT * FROM User LIMIT 1').get();
        if (!row) return null;
        return new User(
            row.id,
            row.pinHash,
            row.pinEnabled,
            row.failedAttempts,
            row.lockoutTimestamp
        );
    }

    /**
     * Creates a new user record in the database with a hashed PIN.
     * Should only be called once during initial setup (signup).
     * PIN is stored as a SHA-256 hash — never as plain text.
     * @param {string} pinHash - The SHA-256 hashed PIN generated by {@link User.hashPin}.
     * @returns {number} The auto-generated ID of the newly created user row.
     */
    createUser(pinHash) {
        const result = this.db.prepare(
            'INSERT INTO User (pinHash, pinEnabled, failedAttempts) VALUES (?, 1, 0)'
        ).run(pinHash);
        return result.lastInsertRowid;
    }

    /**
     * Persists the user's current authentication state back to the database.
     * This is called after every login attempt (success or failure) to ensure
     * that failedAttempts and lockoutTimestamp survive server restarts.
     * @param {User} user - The User model instance with updated state.
     * @returns {void}
     */
    updateUser(user) {
        this.db.prepare(
            'UPDATE User SET failedAttempts = ?, lockoutTimestamp = ? WHERE id = ?'
        ).run(user.failedAttempts, user.lockoutTime, user.id);
    }

    /**
     * Updates the user's PIN hash in the database.
     * Used from the Settings page when the user changes their PIN.
     * Also ensures pinEnabled is set to 1 in case it was previously disabled.
     * @param {number} userId - The ID of the user to update.
     * @param {string} newPinHash - The new SHA-256 hashed PIN.
     * @returns {void}
     */
    updatePin(userId, newPinHash) {
        this.db.prepare(
            'UPDATE User SET pinHash = ?, pinEnabled = 1 WHERE id = ?'
        ).run(newPinHash, userId);
    }
}

export default UserRepository;
