import ExpenseRepository from '@/lib/ExpenseRepository';
import CycleRepository from '@/lib/CycleRepository';
import DailyLimitCalculator from '@/services/DailyLimitCalculator';
import NotificationService from '@/services/NotificationService';
import Expense from '@/models/Expense';
import BudgetCycle from '@/models/BudgetCycle';

const expenseRepo = new ExpenseRepository();
const cycleRepo = new CycleRepository();
const calculator = new DailyLimitCalculator();
const notificationService = new NotificationService();

export async function GET(request) { // Used to fetch-retrieve data from the server
    const { searchParams } = new URL(request.url);
    const cycleId = searchParams.get('cycleId');
    const categoryId = searchParams.get('categoryId');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');

    if(!cycleId){
        return Response.json({ message: 'cycleId is required' }, { status: 400 });
    }

    let expensesData;

    if (categoryId) {
        expensesData = expenseRepo.filterByCategory(cycleId, categoryId);
    } else if(startDate && endDate){
        expensesData = expenseRepo.filterByDateRange(cycleId, startDate, endDate);
    } else {
        expensesData = expenseRepo.getAllByCycle(cycleId);
    }

    const expense = expensesData.map(row => new Expense( // convet raw databse rows into expense model objects
        row.id,
        row.amount,
        row.categoryId,
        row.cycleId,
        row.timestamp,
        row.note
    ));

    return Response.json({ expenses: expense },{status : 200});
}

export async function POST(request){
    const body = await request.json(); // read data coming from UI (request body) and parse it as JSON 
    if (!body.amount || !body.categoryId || !body.cycleId) { // Validate required fields
        return Response.json({ message: 'Missing required fields' }, { status: 400 });
    }

    const newExpense = new Expense(
        null, // ID will be generated by the repository
        body.amount,
        body.categoryId,
        body.cycleId,
        new Date().toISOString(), // SQLite needs a string, not a Date object
        body.note || '' // Default to an empty string if note is not provided
    );

    const expenseId = expenseRepo.insertExpense(newExpense);
    const totalSpent = expenseRepo.getTotalSpent(body.cycleId);
    const activeCycle = cycleRepo.getActiveCycle();

    if (activeCycle) {
        const percentageUsed = calculator.checkThreshold(totalSpent, activeCycle.totalAllowance);                
        const remainingBalance = calculator.calculateRemainingBalance(activeCycle.totalAllowance, totalSpent);
        const cycle = new BudgetCycle(
            activeCycle.id,
            activeCycle.totalAllowance,
            activeCycle.startDate,
            activeCycle.endDate,
            activeCycle.isActive,
            activeCycle.createdAt
        );
        const remainingDays = cycle.getRemainingDays();
        const newDailyLimit = calculator.calculateDailyLimit(remainingBalance, remainingDays);        
      
        const alerts = notificationService.checkAllAlerts(percentageUsed,remainingDays);
        if (alerts.length > 0) {
            console.log("Alerts triggered:", alerts); // Log the triggered alerts
        }
        return Response.json({
            message: 'Expense added successfully',
            expenseId: expenseId,
            totalSpent: totalSpent,
            remainingBalance: remainingBalance.toFixed(2),
            newDailyLimit: newDailyLimit.toFixed(2),
            alerts: alerts
        }, { status: 201 });
    }

    return Response.json({
        message: 'Expense added successfully, but no active cycle found for limit calculations',
        expenseId: expenseId
    }, { status: 201 });
}

export async function PUT(request){ // used to updater or send new data to the server to be saved
    const body = await request.json();
    if (!body.id || !body.amount || !body.categoryId) { // Validate required fields
        return Response.json({ message: 'Missing required fields' }, { status: 400 });
    }

    const updated = expenseRepo.updateExpense(body);
    return Response.json({ message: updated ? 'Expense updated successfully' : 'Expense not found' }, { status: updated ? 200 : 404 });
}


export async function DELETE(request){ // Used to remove data from the server
    const body = await request.json();
    if(!body.id){
        return Response.json({ message: 'Expense ID is required' }, { status: 400 });
    }
    const deleted = expenseRepo.deleteExpense(body.id);
    return Response.json({ message: deleted ? 'Expense deleted successfully' : 'Expense not found' }, { status: deleted ? 200 : 404 });
}