// app/api/cycles/route.js


// New Fixes add : Every request gets its fresh instance every time it's called

import CycleRepository from '@/lib/CycleRepository';
import DailyLimitCalculator from '@/services/DailyLimitCalculator'
import BudgetCycle from '@/models/BudgetCycle';

export async function GET(){ // Used to fetch-retrieve data from the server
    const cycleRepo = new CycleRepository(); //-------------------New Fix
    const cycleData = cycleRepo.getActiveCycle();

    if(!cycleData){
        return Response.json({ message: 'No active cycle found' }, { status: 404 });
    }

    const cycle = new BudgetCycle(
        cycleData.id,
        cycleData.totalAllowance,
        cycleData.startDate,
        cycleData.endDate,
        cycleData.isActive,
        cycleData.createdAt
    );
    return Response.json({ message: 'Active cycle found', cycle },{ status: 200 });
}

export async function POST(request) { // Used to send new data to the server to be saved
    const body = await request.json(); // 
    if (!body.totalAllowance || !body.startDate || !body.endDate) { // Validate required fields
        return Response.json({ message: 'Missing required fields' }, { status: 400 });
    }

    const cycleRepo = new CycleRepository(); // New fresh instance  ------------------- New Fix
    const calculator = new DailyLimitCalculator();//----------------------------New Fix

    const newCycle = new BudgetCycle(
        null, // ID will be generated by the repository
        body.totalAllowance,
        body.startDate,
        body.endDate,
        1, // SQLite needs 1 instead of true
        new Date().toISOString() // SQLite needs a string, not a Date object
    );
    const remainingDays = newCycle.getRemainingDays();
    const remainingBalance = calculator.calculateRemainingBalance(newCycle.totalAllowance, 0); 
    const dailyLimit = calculator.calculateDailyLimit(remainingBalance, remainingDays);
    // Deactivate any existing active cycle first
    const existingCycle = cycleRepo.getActiveCycle();
    if (existingCycle) {
        existingCycle.isActive = 0;
        cycleRepo.updateCycle(existingCycle);
    }

    const cycleid = cycleRepo.insertCycle(newCycle);

    return Response.json({
        message: 'New cycle created successfully',
        cycleid: cycleid,
        dailyLimit: dailyLimit.toFixed(2) 
     }, { status: 201 });   // 201 means Created successfully, and we also return the ID of the newly created cycle and the calculated daily limit for the user to see immediately after creating a new cycle
}

export async function DELETE(request) { // Used to remove data from the server
    const cycleRepo = new CycleRepository();
    const activeCycle = cycleRepo.getActiveCycle();
    if (!activeCycle) {
        return Response.json({ message: 'No active cycle to delete' }, { status: 404 });
    }

    cycleRepo.deleteCycle(activeCycle.id);
    return Response.json({ message: 'Active cycle deleted successfully' }, { status: 200 });
}